
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pmriprficfizzqeexmsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtcmlwcmZpY2ZpenpxZWV4bXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODYyMDEsImV4cCI6MjA1ODY2MjIwMX0.c2hZhnL6TUPDaekgeDBSKBteRiKpwf9k_XmN9BUPmTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Define our own Database type to include new tables
type SupplierRow = {
  id: string;
  name: string;
  contact_name?: string;
  phone?: string;
  email?: string;
  address?: string;
  notes?: string;
  created_at?: string;
};

type PartReceiptRow = {
  id: string;
  item_id: string;
  supplier_id: string;
  invoice_number: string;
  receipt_date: string;
  quantity: number;
  cost?: number;
  notes?: string;
  created_at?: string;
};

type PartTypeRow = {
  id: string;
  name: string;
  description?: string;
  created_at?: string;
};

// Extended Database type
interface CustomDatabase {
  public: {
    Tables: {
      audit_items: {
        Row: {
          actual_quantity: number;
          audit_id: string;
          category: string;
          cost: number;
          created_at: string;
          difference: number;
          id: string;
          location: string;
          name: string;
          system_quantity: number;
        };
      };
      audits: {
        Row: {
          created_at: string;
          date: string;
          discrepancies: number;
          id: string;
          items_count: number;
          location: string;
          user_name: string;
        };
      };
      inventory: {
        Row: {
          category: string;
          cost: number;
          created_at: string;
          description: string;
          id: string;
          lead_time: number;
          location: string;
          min_stock: number;
          name: string;
          part_type_id?: string;
          quantity: number;
        };
      };
      locations: {
        Row: {
          address: string;
          created_at: string;
          id: string;
          manager: string;
          name: string;
        };
      };
      part_receipts: {
        Row: PartReceiptRow;
      };
      part_types: {
        Row: PartTypeRow;
      };
      suppliers: {
        Row: SupplierRow;
      };
      transactions: {
        Row: {
          category: string;
          created_at: string;
          date: string;
          has_proof: boolean;
          id: string;
          item: string;
          location: string;
          notes: string;
          proof_url: string;
          quantity: number;
          type: string;
          user_id: string;
          user_name: string;
          voucher_number?: string;
        };
      };
      users: {
        Row: {
          created_at: string;
          email: string;
          id: string;
          location: string;
          name: string;
          receive_alerts: boolean;
          role: string;
        };
      };
    };
  };
}

// Create and export the supabase client with our custom type
export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
