// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmriprficfizzqeexmsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtcmlwcmZpY2ZpenpxZWV4bXNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwODYyMDEsImV4cCI6MjA1ODY2MjIwMX0.c2hZhnL6TUPDaekgeDBSKBteRiKpwf9k_XmN9BUPmTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);